<?xml version="1.0" encoding="utf-8"?><Database Name="isletimdb" Class="VeritabaniSinifiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TOSHIBA-PC\SQLEXPRESS;Initial Catalog=isletimdb;Persist Security Info=True;User ID=Alpay" SettingsObjectName="sifreleme.Properties.Settings" SettingsPropertyName="isletimdbConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.mesajlar" Member="mesajlars">
    <Type Name="mesajlar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="gonderen_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="alan_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mesaj" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="tarih" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="okundu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.silinenmesajlar" Member="silinenmesajlars">
    <Type Name="silinenmesajlar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="silen_kullanici_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="silinen_kullanici_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tarih" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.kullanicilar" Member="kullanicilars">
    <Type Name="kullanicilar">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="soyad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="kullanici_ad" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="sifre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="mail" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dogum_tarih" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="aktif_durum" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>